# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Dependencies
markdown:         kramdown
highlighter:      rouge

sass:
  style:          compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - vendor/bundle

# Permalinks
# baseurl: ""
permalink: pretty
permalink: /404.md
# relative_permalinks: true
# paginate_path: "/posts/page:num/"
# paginate: 5


collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# collections:
#   projects:
#       output: true


# defaults:
#   -
#     scope:
#       path: projects
#       type: page
#     values:
#       layout: projects



# Server
timezone:         America/New_York
# host:           0.0.0.0
# port:           9001
# url:            "http://yourdomain.com" # the base hostname & protocol for your site
encoding:         UTF-8

gems:
  - jekyll-sitemap
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

# Meta
title:            Ben Sochar
authors:          Ben Sochar
description:      One more developer in Brooklyn.

google_analytics_id: UA-XXXXXXXXX
google_site_verification:

# Contact vars
email:            bsochar@gmail.com
twitter_username: bensochar
github_username:  bensochar
