# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Dependencies
markdown:         kramdown
highlighter:      rouge

sass:
  style:          compressed

#
# Files to keep or not
include:
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - vendor/bundle

#
# Permalinks
# baseurl: ""
permalink: pretty
# permalink: /404.md
# relative_permalinks: true
# paginate_path: "/posts/page:num/"
# paginate: 5
collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

#
# Server
timezone:         America/New_York
# host:           0.0.0.0
# port:           9001
url:              "http://localhost:4000" # the base hostname & protocol for your site
encoding:         UTF-8
#
# Gems
gems:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-mentions
  - octopress-minify-html
  # - octopress-image-tag
  # - octopress-social

jekyll-mentions:
  base_url: https://twitter.com


repository: bensochar/bensochar.github.io

#
# Meta
title:                Ben Sochar
authors:              Ben Sochar
description_short:    Full Stack
description:          Brooklyn-based experienced full-stack web developer always eager for more.
google_analytics:     UA-80048348-1
google_verification:  bNxPt9aX1r_Bm1LrjHHrnHrmx8xx1ZSbSidXWvq2og0
bing_verification:    F2755313519F06188F14B44E05940408
favicon_path:         /assets/images/meta/
#
# Contact vars
email:              bsochar@gmail.com
twitter_username:   bensochar
github_username:    bensochar
instagram_username: bensochar
linkedin_username:  bensochar
