# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Dependencies
markdown:         kramdown
highlighter:      rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight p-3 mx-lg-n5 p-lg-5 mb-0'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

sass:
  style:          compressed

#
# Files to keep or not
include:
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - vendor/bundle

#
# Permalinks
# baseurl: ""
permalink: pretty
# permalink: /404.md
# relative_permalinks: true
# paginate_path: "/posts/page:num/"
# paginate: 5
collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

#
# Server
timezone:         America/New_York
# host:           0.0.0.0
# port:           9001
url:              "https://bensochar.com" # the base hostname & protocol for your site
encoding:         UTF-8
#
# Gems
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-mentions
  - octopress-minify-html
  # - octopress-image-tag
  - octopress-social

jekyll-mentions:
  base_url: https://twitter.com


repository: bensochar/bensochar.github.io

#
# Meta
title:                Ben Sochar
author:               Ben Sochar
author_alt:           Benjamin Sochar
author_first_name:    Ben
author_last_name:     Sochar
authors:              Ben Sochar
description_short:    Full Stack Technical Lead
description:          Brooklyn-based experienced full-stack web developer & Technical Lead. Always eager for more.
google_analytics:     G-8DYTE8SXCG
google_verification:  bNxPt9aX1r_Bm1LrjHHrnHrmx8xx1ZSbSidXWvq2og0
bing_verification:    F2755313519F06188F14B44E05940408
favicon_path:         /images/meta/
locality:             Brooklyn
region:               NY
theme_color:          '#2828c6'
fb_admin:             6814681
#
# Contact vars
email:              bsochar@gmail.com
twitter_username:   bensochar
github_username:    bensochar
instagram_username: bensochar
linkedin_username:  bensochar
bluesky_username:   bensochar.bsky.social
mastodon_username:  '@bensochar'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - rakefile
  - tmp



